### ISSUE TITLE
Insert command bug

### ISSUE THREAD

**Issue by TheHackerLxr** [kohls-admin/kohls-admin#133]
### Did you check for existing issues?

- [X] I have searched the open and **closed** bugs.

### Platform

PC

### Version

0.1

### Description

![image](https://github.com/user-attachments/assets/f5f20771-57b7-47c7-b4d5-96ffa72faf63)

insert command gives an error and does not execute

### Repro

Try to take some model from the store (its ID) and enter it through the command, it does not insert into the game

### Details

![image](https://github.com/user-attachments/assets/94266f70-1293-40d4-a1eb-4f5f9e755949)

**Comment by Lucatacos** [comment]
It was a roblox bug and it has been fixed: https://devforum.roblox.com/t/corepackages-attempt-to-call-a-table-value-error/3189042

**Comment by TheHackerLxr** [comment]
> It was a roblox bug and it has been fixed: https://devforum.roblox.com/t/corepackages-attempt-to-call-a-table-value-error/3189042

![image](https://github.com/user-attachments/assets/63a41784-03d3-43d8-a19b-a7692ca7afb8)
Still not fixed, what you talking about?

**Comment by Lucatacos** [comment]
> > It was a roblox bug and it has been fixed: https://devforum.roblox.com/t/corepackages-attempt-to-call-a-table-value-error/3189042
> 
> ![image](https://private-user-images.githubusercontent.com/88975442/376057457-63a41784-03d3-43d8-a19b-a7692ca7afb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDk1MjksIm5iZiI6MTcyODg0OTIyOSwicGF0aCI6Ii84ODk3NTQ0Mi8zNzYwNTc0NTctNjNhNDE3ODQtMDNkMy00M2Q4LWExOWItYTc2OTJjYTdhZmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDE5NTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTE3NjJkZDlkZDNjMjJjMjcxN2FiOWM4NTIxOTM5YTBjMjBmMDJlZDIzMDVjY2UwN2JkMTZlMmU1NjQ0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YCD8rKAPZQc3j5C9k9VN9yJ1pjGl59wktc4dH4YOgaU)
> 
> Still not fixed, what you talking about?

Oh it’s weird since the last version , I’m not getting the error now , did you tried to re-add the model up-to-date
